### ISSUE TITLE
Every first time get pokemon information this will happend

### ISSUE THREAD

**Issue by milowei** [tuttarealstep/PokeGOAPI-PHP#5]
$PokemonGoAPI->getInventories()->getPokeBank()->getPokemonById(\POGOProtos\Enums\PokemonId::PIDGEY);

Fatal error: Uncaught Error: Call to a member function getInventoryItemsArray() on null in /Applications/XAMPP/xamppfiles/htdocs/pkg2/src/PokemonGoAPI/Api/Inventory/Inventories.php:68 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/pkg2/src/PokemonGoAPI/Api/PokemonGoAPI.php(49): PokemonGoAPI\Api\Inventory\Inventories->updateInventories(false) #1 /Applications/XAMPP/xamppfiles/htdocs/pkg2/examples/CheckPidgeyExample.php(20): PokemonGoAPI\Api\PokemonGoAPI->__construct(Array) #2 /Applications/XAMPP/xamppfiles/htdocs/pkg2/examples/CheckPidgeyExample.php(41): CheckPidgeyExample->run() #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/pkg2/src/PokemonGoAPI/Api/Inventory/Inventories.php on line 68

After I refresh the page and this will be fixed;

**Comment by tuttarealstep** [comment]
What is your php version? This happen everytime?

**Comment by milowei** [comment]
php 7, not every time, After about 3-5 min or change another account to login this will be happend

**Comment by tuttarealstep** [comment]
Now I check the same code and if this happen to me too.
